[pytest]
addopts = -v --tb=short --alluredir=allure-results
testpaths = ui/tests api/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
markers =
    ui: UI tests for Sauce Demo
    api: API tests for Restful Booker
